default_stages: [pre-commit]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [ --strict ]
        additional_dependencies: 
          - pydantic==1.9
          - pytest==8.1.0
          - importlib_resources==6.1.1
          - jinja2==3.1.3
